local messagingNotes = {}

messagingNotes.messagingGlobal = {
	MsgType_PlayerParkSavedDeletedMessage = 3,
}

messagingNotes.messagesTarget = {
    MsgType_GuestCashModifiedMessage = 97,
    MsgType_GuestDestinationBecameAccessibleMessage = 99,
    MsgType_GuestDrowningStoppedMessage = 101,
    MsgType_GuestGroupEnteredParkMessage = 107,
    MsgType_GuestHiddenMessage = 108,
    MsgType_GuestInventoryAddedRemovedMessage = 109,
    MsgType_GuestInventoryChangedMessage = 110,
    --MsgType_GuestMoodRecordedMessage = 112,
    MsgType_GuestPhysicsIncidentEndedMessage = 115,
    MsgType_GuestSuccessfulRideMessage = 118,
    MsgType_GuestSunburnMessage = 119,
    MsgType_GuestThoughtsUpdatedMessage = 120,
    MsgType_GuestGroupEnteredHotelMessage = 134,
    MsgType_GuestGroupLeftHotelMessage = 135,
	MsgType_UpdateRideStatsMessage = 64,
	MsgType_PoolStatsUpdatedMessage = 123,
	MsgType_RideEditedMessage = 59,
	MsgType_TrainAddedRemovedMessage = 60,
	MsgType_TrainInStationMessage = 62,
	MsgType_TrainCanLeaveMessage = 54,
	MsgType_RideQueueUpdatedMessage = 315,
	--MsgType_CrowdFeatureAddedMessage = 293,
	--MsgType_CrowdFeatureMovedMessage = 294,
	--MsgType_CrowdFeatureRemovedMessage = 295,
	MsgType_RequestModifyAllNeedsMessage = 126,
    MsgType_EntranceExitDeletedMessage = 318,
	MsgType_ParkDatastoreUpdateMessage = 153,
	MsgType_GroupRequestDebugPoolEntryMessage = 91,
    MsgType_EntranceExitPickedUpPlacedMessage = 319,
    MsgType_StationAccessChangedMessage = 320,
	MsgType_StatsDatastoreUpdateMessage = 165,
	MsgType_RideStatsUpdatedMessage = 187,
	MsgType_StationStatsUpdatedMessage = 192,
    MsgType_GameLicenceUpdatedMessage = 21,
    MsgType_NewWorkshopItemAvailableMessage = 22,
    MsgType_ModItemAvailabilityMessage = 22,
    MsgType_ModUpdateAllProgressMessage = 23,
    MsgType_SubscriptionListReadyMessage = 24,
    MsgType_CinematicEventMessage = 370,
    MsgType_UndoRedoCompletedMessage = 371,
    --MsgType_DataStreamMessage = 379,
    --MsgType_ComponentsActivatedForEntitiesMessage = 9,
    --MsgType_ComponentsHaveBeenRemovedFromEntitiesMessage = 381,
    --MsgType_EntitiesAboutToBeDestroyedMessage = 383,
    --MsgType_SpatialVolumeChangedMessage = 387,
    --MsgType_EntityDestructionRequestedMessage = 395,
    --MsgType_ComponentsAboutToBeRemovedFromEntitiesMessage = 396,
    --MsgType_ComponentsAddedToEntitiesMessage = 397,
}

messagingNotes.messages = {
	"ChangeType_ItemPrice",
	"ChangeType_Sold",
	"ChangeType_ExtraUsed",
	"ChangeType_CustomName",
	"ChangeType_FullReset",
	"MsgType_PlayerBlueprintSavedDeletedMessage",
	"MsgType_PlayerParkSavedDeletedMessage",
	"MsgType_GameServerConnectionChangedMessage",
	"MsgType_IRCConnectionChangedMessage",
	"MsgType_PoolColourDataChangeMessage",
	"MsgType_DLCLicencesChangedMessage",
	"MsgType_ParkThemingUpdatedMessage",
	"MsgType_PuppetUpdatedMessage",
	"MsgType_FacilityClosedMessage",
	"MsgType_FacilityDemolishedMessage",
	"MsgType_FacilityInventoryDataChangedMessage",
	"MsgType_FacilityDayOpenedChangedMessage",
	"MsgType_FacilityOpenedMessage",
	"MsgType_FacilityPlacedMessage",
	"MsgType_FacilityRunningCostChangedMessage",
	"MsgType_FacilityServiceStateChangedMessage",
	"MsgType_GroupEnteredBenchMessage",
	"MsgType_GroupRejectedFacilityMessage",
	"MsgType_ShopInventoryItemChangedMessage",
	"MsgType_ShopItemPriceChangedMessage",
	"MsgType_ShopFairPriceMessage",
	"MsgType_ShopPriceSyncMessage",
	"MsgType_SmallAttractionProbabilityChangedMessage",
	"MsgType_RideVariationChangedMessage",
	"MsgType_TrainCanLeaveMessage",
	"MsgType_FlumeChangedPlatformMessage",
	"MsgType_RideEditedMessage",
	"MsgType_TrainAddedRemovedMessage",
	"MsgType_TrainInStationMessage",
	"MsgType_UpdateRideStatsMessage",
	"MsgType_FirstTimeEntityTypeSelectedMessage",
	"MsgType_MultiSelectionMessage",
	"MsgType_PlayerBonusLockStateChangedMessage",
	"MsgType_SimulationSpeedChangedMessage",
	"MsgType_StartScreenGlobeMovementCompleted",
	"MsgType_TutorialEventMessage",
	"MsgType_GroupRequestDebugPoolEntryMessage",
	"MsgType_GuestCashModifiedMessage",
	"MsgType_GuestDestinationBecameAccessibleMessage",
	"MsgType_GuestDrowningStoppedMessage",
	"MsgType_GuestGroupEnteredParkMessage",
	"MsgType_GuestHiddenMessage",
	"MsgType_GuestInventoryAddedRemovedMessage",
	"MsgType_GuestInventoryChangedMessage",
	"MsgType_GuestMoodRecordedMessage",
	"MsgType_GuestPhysicsIncidentEndedMessage",
	"MsgType_GuestSuccessfulRideMessage",
	"MsgType_GuestSunburnMessage",
	"MsgType_GuestThoughtsUpdatedMessage",
	"MsgType_PoolStatsUpdatedMessage",
	"MsgType_RequestModifyAllNeedsMessage",
	"MsgType_ShowDrowningGroupIconMessage",
	"MsgType_FacilityTicketPriceChangedMessage",
	"MsgType_AdvertisedDestinationChangedMessage",
	"MsgType_CashSpentMessage",
	"MsgType_CoasterFrictionOptionChangedMessage",
	"MsgType_ExtraTrainTypeOptionChangedMessage",
	"MsgType_GuestGroupEnteredHotelMessage",
	"MsgType_GuestGroupLeftHotelMessage",
	"MsgType_HotelPerksChangedMessage",
	"MsgType_HotelPlacementPartReadyMessage",
	"MsgType_HotelRoomCountChangedMessage",
	"MsgType_HotelRoomDataChangedMessage",
	"MsgType_HotelRoomPlacedMessage",
	"MsgType_LoadingScreenFinishedMessage",
	"MsgType_LoanRepaidMessage",
	"MsgType_LoansPaymentPreviewMessage",
	"MsgType_LoansPreviewMessage",
	"MsgType_LoansStageChangedMessage",
	"MsgType_LoansUpdateMessage",
	"MsgType_LocationPointUpdatedMessage",
	"MsgType_MarketingUpdateMessage",
	"MsgType_ParkBoundaryPlotUnlockStateChangedMessage",
	"MsgType_ParkDatastoreUpdateMessage",
	"MsgType_ParkManagementSecurityUpdateMessage",
	"MsgType_ParkManagementSpecialEffectsUpdateMessage",
	"MsgType_ParkNotificationMessage",
	"MsgType_ParkRatingsAtNewDayMessage",
	"MsgType_RequestParkZoneSelectionModeMessage",
	"MsgType_HotelExtensionRenamedMessage",
	"MsgType_SaveSuspendedMessage",
	"MsgType_SettingsUnitsChangeMessage",
	"MsgType_StaffMoraleFeaturesChanged",
	"MsgType_StatsDatastoreUpdateMessage",
	"MsgType_MissingUserContentMessage",
	"MsgType_PlacementPartCommittedMessage",
	"MsgType_HeatmapOptionChangedMessage",
	"MsgType_NonStopTrainCountChangedMessage",
	"MsgType_RideCameraEnteredOrExited",
	"MsgType_RideDeletedMessage",
	"MsgType_RideMaterialChangedMessage",
	"MsgType_RideObjectiveLinksChanged",
	"MsgType_RideOpenStateChangedMessage",
	"MsgType_RideOperatorChangedMessage",
	"MsgType_RideStationDeletedMessage",
	"MsgType_RideStatsUpdatedMessage",
	"MsgType_StationMaintenanceLevelUpdatedMessage",
	"MsgType_StationServiceStateChangedMessage",
	"MsgType_StationStatsUpdatedMessage",
	"MsgType_StationTicketFairPriceChangedMessage",
	"MsgType_TrainActivatedMessage",
	"MsgType_TrainTypeChangedMessage",
	"MsgType_UpdateFlumeStatsMessage",
	"MsgType_ParkEntrancePlacedMessage",
	"MsgType_SceneryPlacedMessage",
	"MsgType_MusicTrackChangedMessage",
	"MsgType_SignTextChangedMessage",
	"MsgType_DisplaySequencerPlacedMessage",
	"MsgType_RideCamPropDataChangedMessage",
	"MsgType_SequencerPropDataChangedMessage",
	"MsgType_TimeMachineChangedMessage",
	"MsgType_TriggerTargetPropDataChangedMessage",
	"MsgType_SequenceChangedMessage",
	"MsgType_LifeguardAssignedAtPostMessage",
	"MsgType_LifeguardPostUpdatedMessage",
	"MsgType_RideAttendantAssignmentChangedMessage",
	"MsgType_StaffAtHomeStatusChangeMessage",
	"MsgType_StaffBuildingAvailableMessage",
	"MsgType_StaffBuildingChangedMessage",
	"MsgType_StaffCostMultiplierChangedMessage",
	"MsgType_StaffCreatedOrDeletedMessage",
	"MsgType_StaffFlexiColoursChangedMessage",
	"MsgType_StaffLeftStaffBuildingMessage",
	"MsgType_StaffLeftWorkshopMessage",
	"MsgType_StaffMemberMoraleChangedMessage",
	"MsgType_StaffMemberOnStrikeMessage",
	"MsgType_StaffMemberPatrolZoneChangedMessage",
	"MsgType_StaffMemberQuitMessage",
	"MsgType_StaffMemberRestInfluenceChangedMessage",
	"MsgType_StaffMemberTaskChangedMessage",
	"MsgType_StaffMemberTrainingDateChangedMessage",
	"MsgType_StaffMemberTrainingLevelChangedMessage",
	"MsgType_StaffMemberWageChangedMessage",
	"MsgType_StaffRestStatusChangedMessage",
	"MsgType_StaffScheduleBuildingFilterChangedMessage",
	"MsgType_StaffScheduleCopyBlockMessage",
	"MsgType_StaffScheduleCurrentBlockChangeMessage",
	"MsgType_StaffScheduledLevelUpMessage",
	"MsgType_StaffScheduleParkZoneChangeMessage",
	"MsgType_StaffScheduleStaffFilterChangedMessage",
	"MsgType_StaffScheduleParkZoneFilterChangedMessage",
	"MsgType_StaffScheduleStaffTypeFilterChangedMessage",
	"MsgType_StaffScheduleErrorChangeMessage",
	"MsgType_StaffScheduleTaskChangeMessage",
	"MsgType_StaffScheduleViewModeFilterChangedMessage",
	"MsgType_StaffSpecificRestLocationChangeMessage",
	"MsgType_StaffSpecificJobLocationChangeMessage",
	"MsgType_StaffThoughtsChangedMessage",
	"MsgType_StaffTrainingDisabledMessage",
	"MsgType_JanitorHeadingToFacilityChangedMessage",
	"MsgType_VendorHeadingToFacilityMessage",
	"MsgType_VendorLeftFacilityMessage",
	"MsgType_WorkshopChangedMessage",
	"MsgType_NodePurchaseUpdatedMessage",
	"MsgType_ResearchPointsUpdatedMessage",
	"MsgType_CoasterStationSelectedFromBrowserMessage",
	"MsgType_PlayerSubmitShootingScoreMessage",
	"MsgType_RaceOverMessage",
	"MsgType_ShootableTargetPlacementPartReadyMessage",
	"MsgType_UseLooseTrackRestrictionsMessage",
	"MsgType_UserRenameMessage",
	"MsgType_GroupExitedBenchMessage",
	"MsgType_GroupExitedShopMessage",
	"MsgType_OpenStateChangedMessage",
	"MsgType_CrowdFeatureAddedMessage",
	"MsgType_CrowdFeatureMovedMessage",
	"MsgType_CrowdFeatureRemovedMessage",
	"MsgType_FlatRideCreatedMessage",
	"MsgType_RideQueueUpdatedMessage",
	"MsgType_EntranceExitDeletedMessage",
	"MsgType_EntranceExitPickedUpPlacedMessage",
	"MsgType_StationAccessChangedMessage",
	"MsgType_StationTicketPremiumTargetQueueChangedMessage",
	"MsgType_StationTicketPriceChangedMessage",
	"MsgType_StationTicketPriceStateChangedMessage",
	"MsgType_VehicleModeChangedMessage",
	"MsgType_TestMessage2",
	"MsgType_ComplexItemMembershipChangedMessage",
	"MsgType_ComplexMembershipChangedMessage",
	"MsgType_CustomTextureRidePhotoMessage",
	"MsgType_DifficultySettingUpdatedMessage",
	"MsgType_HighPriorityStaffAlertAssignmentMessage",
	"MsgType_MaterialChangedGameMessage",
	"MsgType_ParkTimeBlockIndexChangedMessage",
	"MsgType_ParkTimeRegularMessage",
	"MsgType_ParkTimeStartOfMonthMessage",
	"MsgType_ParkTimeNewDayMessage",
	"MsgType_NextGuestMetricTickMessage",
	"MsgType_RenderEffectChangedMessage",
	"MsgType_SandboxSettingsUpdatedMessage",
	"MsgType_SecurityGuardAssignedAtPostMessage",
	"MsgType_SecurityPostUpdatedMessage",
	"MsgType_SouvenirShopDisplayedItemsInComplexChangedMessage",
	"MsgType_ParkZoneAreaChangedMessage",
	"MsgType_ParkZoneCreatedOrDeletedMessage",
	"MsgType_ParkZoneIconChangedMessage",
	"MsgType_ParkZoneLockStateChangedMessage",
	"MsgType_ParkZoneMembershipChangedMessage",
	"MsgType_ParkZoneNameChangedMessage",
	"MsgType_ParkZoneShapeChangedMessage",
	"MsgType_ParkZoneStyleChangedMessage",
	"MsgType_ParkZoneVisibilityChangedMessage",
	"MsgType_ParkZoneWidgetChangedMessage",
	"MsgType_ParkZoneThemingUpdatedMessage",
	"MsgType_UpdateUtilityConsumptionFromDistributorMessage",
	"MsgType_FacilityUtilityChangedMessage",
	"MsgType_OnPlotSelectedMessage",
	"MsgType_PoolEntrancePlacedRemovedMessage",
	"MsgType_UtilitiesVisibilityChangedMessage",
	"MsgType_ScenarioCompleteMessage",
	"MsgType_SceneryBelongingOwnerAttachmentsChangedMessage",
	"MsgType_SceneryPlatformOwnerAttachmentsChangedMessage",
	"MsgType_RestaurantMonitorUpdateMessage",
	"MsgType_SouvenirShopDisplayItemChangedMessage",
	"MsgType_PhotoKioskRideLinkChangedMessage",
	"MsgType_RidePhotoQualityChangedMessage",
	"ParkBoundaryPlotUnlockStateChangedMessage_Purchased",
	"ParkBoundaryPlotUnlockStateChangedMessage_NarrativeUnlock",
	"ParkBoundaryPlotUnlockStateChangedMessage_UnlockForPurchase",
	"SceneryPlacedMessage_Piece",
	"SceneryPlacedMessage_Blueprint",
	"TutorialEventType_BuildNeedSatisfaction",
	"TutorialEventType_HiredStaff",
	"TutorialEventType_OpenedStaffManagementUI",
	"TutorialEventType_PlaceBench",
	"TutorialEventType_PlaceSunLounger",
	"TutorialEventType_PlaceBin",
	"TutorialEventType_PlaceRide",
	"TutorialEventType_PlaceRideExitPath",
	"TutorialEventType_PlaceScenery",
	"TutorialEventType_PlaceStaffBuilding",
	"TutorialEventType_PreviewRide",
	"TutorialEventType_StaffSalaryIncreased",
	"TutorialEventType_TrainedStaff",
	"TutorialEventType_ViewGuestNeeds",
	"TutorialEventType_ViewGuestThoughts",
	"TutorialEventType_ViewParkRatingBreakdown",
	"TutorialEventType_ViewFinancePanel",
	"TutorialEventType_ViewGuestThoughtsSummary",
	"TutorialEventType_ViewShopsList",
	"TutorialEventType_ViewFacilitiesList",
	"TutorialEventType_ViewNotificationList",
	"TutorialEventType_FixRide",
	"TutorialEventType_ViewCoasterBrowser",
	"TutorialEventType_CoasterPopupOpenTestingTab",
	"TutorialEventType_CoasterPopupVewTestingResults",
	"TutorialEventType_CoasterPopupVewTestingHeatmaps",
	"TutorialEventType_ViewPopUpMarker",
	"TutorialEventType_ClosePopUpMarker",
	"TutorialEventType_PlaceFlumePlatform",
	"TutorialEventType_ChooseFlatRideBluePrintFromBrowser",
	"TutorialEventType_ChooseTrackedRideBluePrintFromBrowser",
	"TutorialEventType_ChooseCoasterBluePrintFromBrowser",
	"TutorialEventType_SaveBlueprint",
	"TutorialEventType_EnterCoasterCamera",
	"TutorialEventType_ViewStaffMorale",
	"TutorialEventType_InspectStaffInfoPanel",
	"TutorialEventType_ViewUtilityGeneratorInfoPanel",
	"TutorialEventType_StaffFullyRested",
	"TutorialEventType_PlaceFlatRideBlueprint",
	"TutorialEventType_PlaceTrackedRideBlueprint",
	"TutorialEventType_PlaceCoasterBlueprint",
	"TutorialEventType_PlacePoolBlueprint",
	"TutorialEventType_InspectParkExpansion",
	"TutorialEventType_InspectParkZone",
	"TutorialEventType_SelectFlumeFromCustomBrowser",
	"TutorialEventType_PlaceFlume",
	"TutorialEventType_PlaceFlumeEndPiece",
	"TutorialEventType_PlaceFlumeTrack",
	"TutorialEventType_InspectPoolSafetyInfoPanel",
	"TutorialEventType_InspectParkManagementResearchTab",
	"TutorialEventType_ClearEnforcedPlacementAreaOfEntities",
}

return messagingNotes